### ISSUE TITLE
TerminationGracePeriod Support

### ISSUE THREAD

**Issue by AdheipSingh** [druid-io/druid-operator#10]
Currently termination grace period is set to default ie 30 sec. Can we add support in the spec so that we can modify the grace period.

**Comment by akashdw** [comment]
@AdheipSingh sounds good, can you share the proposal for the same?

**Comment by AdheipSingh** [comment]
so by default we are not using an pre-deletion hook, so the SIGTERM is responsible for killing all the processes in the container when we are deleting the pod, by default k8s has set a grace period to 30 sec, this parameter should be configurable by the end user in case the user wants to add more time for grace period. Since middle managers are ingesting data plus have some external storages such as s3 i prefer to keep the grace period more than default.

**Comment by AdheipSingh** [comment]
Ill Add a PR for the same :)
