### ISSUE TITLE
Watch deployments/Sts/services with watcher

### ISSUE THREAD

**Issue by AdheipSingh** [druid-io/druid-operator#108]
- The operator is only watching Druid CR, which is fine, but if someone directly edits the deployment, it should make sure the desiredState remains with CR. Until and update is run it does not change the state.

- Druid Operator should watch for deployments/sts/services/pdb etc resources which it creates and make sure their state is met.

@himanshug any specific reason for commenting out the watchers for deployments/sts etc ? i see a TODO on the comment though :) 
https://github.com/druid-io/druid-operator/blob/master/pkg/controller/druid/druid_controller.go#L56

**Comment by himanshug** [comment]
that TODO comment was part of auto generated code :)

in the old days, for debugging I would manually update the statefulSets and wouldn't want operator to change things (`ignored` flag did not exist back then) ... after I was done with my investigation, I would typically end up making some update to druid spec (or restart the operator pod) that would do a reconciliation and bring things back to normal.

anyways, manual updates to resources created by operator is not regular workflow and is done by admins in special circumstances ... so it didn't make much sense to add so many watchers (not sure what the cost of adding additional watches it) and running reconciliation loop many extra times where it wouldn't change anything in normal state.

also, IIRC, If a StatefulSet was managing pods and user manually changed label, image etc in the pod then StatefulSet doesn't automatically reconcile it

**Comment by AdheipSingh** [comment]
> that TODO comment was part of auto generated code :)

ha i see.

> so it didn't make much sense to add so many watchers (not sure what the cost of adding additional watches it) and running reconciliation loop many extra times where it wouldn't change anything in normal state.

k8s follows edge level triggers than level driven trigger ( kind of polling ) , the event handler will be triggered only when an event comes from informers,  regardless loop will be triggered for watchers though :| 

My only concern is users manually editing deployments/sts and then some one updating CR/Helm etc causes a bit confusion. State should be enforced, atleast we could watch for sts/deployments/ingress OR we can add flag if someone wants to enable it or not. 
 
> if a StatefulSet was managing pods and user manually changed label, image etc in the pod then StatefulSet doesn't automatically reconcile it

Statefulset will allow changing the image since its in containerSpec, it does not allow changing anything in volumeclaim, pod management and metadata, you can change podSpec though :)

**Comment by himanshug** [comment]
> Statefulset will allow changing the image since its in containerSpec, it does not allow changing anything in volumeclaim, pod management and metadata, you can change podSpec though :)

point I was trying to make is that StatefulSet controller creates Pods , if you manually change the Pods then StatefulSet wouldn't reconcile those.

we can probably watch  deployments/Sts/services  etc etc too but there are so many things to watch only for the special case that user is manually changing stuff which I assume to be special case where user knows what they are doing.. or am I missing the use case?

**Comment by AdheipSingh** [comment]
>  I assume to be special case where user knows what they are doing.

On a lighter note, That's a tough call, you never know what users are up to on k8s clusters :rofl: 

Regardless,

1. Like a pod is managed by replica set > managed by deployment, same way operator is responsible for maintaing the state for all the sub-resources it creates.
2. The major issue i see in existing env is replica counts are frequently changed as and when ingestion kicks of or heavy queries are served. In those scenarios users come and scale deploy/sts, which results in a mismatch of CR and the deploy/sts spec, and in case an automated CI runs to update/upgrade the cluster the replica count goes back to operator. 
3. I just want to make sure that NO state changes can be done on sub-resources. If a user wants to change anything that should be only and only done on the CR.
4. Just wanted to enforce that, currently there's a free hand to mess up deploy/sts which draws confusion plus having watchers for atleast deployments + sts + svc + ingress is must. 
5. Plus till the time event does not come from informer, the watcher is not adding any cost. 
6. If any one deletes a deploy/sts ( which i have seen happening :disappointed:  ) atleast the operator can re-create it and make sure things are stable there.

These are the main concerns. I hope i am able to explain :smile:

**Comment by himanshug** [comment]
>  users come and scale deploy/sts, which results in a mismatch of CR

that does sound like a dev workflow issue, they should make the change to druid CR instead.

anyways, I doubt if those additional watches would help you because a reconciliation is triggered every 10secs anyways... it doesn't reset the changed replica count because current operator code does the updates only if things changed in the druid CR or if a druid-operator managed resource is deleted.

**Comment by AdheipSingh** [comment]
yeah we will need to match the spec's such as currentSts = nextSts and update the spec. That should be done by the operator, i believe that should be  the default behaviour of operator.

**Comment by himanshug** [comment]
I will try to introduce some framework to enable this shortly, so that behavior can be modified when makes sense.

regardless, additional watches wouldn't be needed I think.
