### ISSUE TITLE
Task/Peon logs to stdout

### ISSUE THREAD

**Issue by cosmic-chichu** [druid-io/druid-operator#119]
#### Version Info:
- druid v0.20.0
- druid-operator-0.0.3.

I would like to route my task/peon logs to stdout as well. Currently, the task logs are available on the UI and deep storage but additional config to route them to stdout would help capturing it on services like Splunk.

After due reading on druid community I added the following config to my tasks with no luck: 
`log4j.configurationFile=/opt/druid/conf/druid/cluster/data/middleManager/log4j2.xml` 
Any pointers as to what I'm missing? Also based on docs, the tasks should pick up middle manager configs in which case adding the above line would be redundant. 

I have the following configuration for my tasks: 
```druid.indexer.runner.javaOptsArray=["-server","-Xms500M","-Xmx500M","-XX:MaxDirectMemorySize=3600000000","-Duser.timezone=UTC","-Dfile.encoding=UTF-8","-XX:+UseGCLogFileRotation","-XX:NumberOfGCLogFiles=50","-XX:GCLogFileSize=10m","-XX:+ExitOnOutOfMemoryError","-XX:+UseG1GC","-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager","-Dlog4j.configurationFile=/opt/druid/conf/druid/cluster/data/middleManager/log4j2.xml","-Xloggc:/druid/data/logs/peon.gc.%t.%p.log"]```

**Comment by himanshug** [comment]
I don't think this is a druid-operator concern per se.

AFAIK, "Task Log" can not be sent to stdout of the MM process. But, this question is more appropriate for Druid instead.
