### ISSUE TITLE
Deletion of Unmounted PVC's

### ISSUE THREAD

**Issue by AdheipSingh** [druid-io/druid-operator#136]
### Scenario
- when ingestion kicks of i scale my MM to  10 ( all statefulsets ), now i have 10 pvc for 10 MM Statefulsets
- when done i scale down MM to 1, now i have 1 MM statefulsets and 10 PVC of which 9 pvc are unmounted .

### ISSUE
- These 9 pvc's shall exist till the time the CR is deleted ( where finalizer shall come into play and the hook deletes the pvc's ).

### SOLUTION
- The 9 pvc's are of no / little use when we scale down druid nodes, the operator should ideally remove the pvc which are not mounted by running a check on each reconciliation loop.
- This way all the pvc's which are hanging up are cleaned.

@himanshug

**Comment by himanshug** [comment]
what thing decreases the replica count to scale down?

but, yeah, that is OK as a workaround for now.

**Comment by AdheipSingh** [comment]
> what thing decreases the replica count to scale down?

its manual a step. Ex: when i ain't doing any ingestion, i scale down MM ( change nodeSpec.Replicas ). The PVC's are now unmounted ( since MM is STS ) and of no  use. In that case we can delete the pvc's.

**Comment by himanshug** [comment]
yeah, sure, deleting unused PVCs continuously makes sense.
