### ISSUE TITLE
Getting started - cannot follow instructions to get started on e.g. EKS

### ISSUE THREAD

**Issue by resonating-sirsh** [druid-io/druid-operator#148]
Im having a little trouble getting started and would greatly appreciate some clarification on a few things. 
I installed the operator - I manually built the docker image and pushed it to ECR and edited the operator.yaml to point to that - but otherwise followed the steps to deploy the operator. This seems to be running.

I wanted to try an example on EKS. As the documentation said, the tiny example does not work with local "deep" storage. I tried working with the hpa example and setting up the S3 but im not doing it right.

The problem i see is in the POD `describe` where 

```bash
fargate-scheduler  Pod not supported on Fargate: volumes not supported: deepstorage-volume is of an unsupported volume Type
```
I guess what I would like to see is a basic example of something that _will_ run on EKS to get started as I am unsure about what config to change to get started. Theres a lot for a first encounter :) and it would be good to have a "beachhead" from which to start playing with the different settings. 

Additionally, what is the recommended command to delete a druid cluster/deployment such as druid-tiny-cluster?

**Comment by AdheipSingh** [comment]
@resonating-sirsh 

Not sure what version of eks are you running, that might not support ```DirectoryOrCreate``` in the tiny-cluster. Regardless i recommend checking out these examples for understanding on how to design the spec.
 For running druid you'll need to customize your deepstorage and metadata, you can add volumes to each of your nodeTypes like this https://gist.github.com/AdheipSingh/434dcbb061c5114af174fefcf40e45f1#file-gke-druid-yaml-L93

I also recommend you to start with some docs and understand the various configurations/features supported, for more detailed design you can check the https://github.com/druid-io/druid-operator/blob/master/apis/druid/v1alpha1/druid_types.go

To delete a cluster, you can get the CR and then delete it, you can also directly to delete to the manifest ie kubectl delete -f tiny.cluster.yaml
```
kubectl get druid -n namespace
kubectl delete druid mydruid -n namespace
```

**Comment by resonating-sirsh** [comment]
Thanks @AdheipSingh - example is super useful.
...Ah ok, i was missing the right namespace but thought it was something like this - thanks for this!
