### ISSUE TITLE
Release 0.0.6 druid operator

### ISSUE THREAD

**Issue by AdheipSingh** [druid-io/druid-operator#168]
- Finalizer Added for pvc cleanUp
- Helm Chart
- Ingress updated networking v1beta1
- delete orhpan pvc feature and bug fix
- HPA updated to v2beta2
- HPA Operator bug fix

**Comment by AdheipSingh** [comment]
@himanshug

**Comment by himanshug** [comment]
how far are we from finishing https://github.com/druid-io/druid-operator/pull/167 ? it would be nice to include that.

**Comment by himanshug** [comment]
@AdheipSingh do you want to get something else in before we release 0.6.0 ?

**Comment by AdheipSingh** [comment]
@himanshug i am still running tests on   https://github.com/druid-io/druid-operator/pull/175 this inhouse, once confirmed will take this out of draft. 

So for  now we are good for the release.

**Comment by himanshug** [comment]
0.0.6 is pushed. Thanks.
