### ISSUE TITLE
Question: deploying across multiple namespaces

### ISSUE THREAD

**Issue by EwanValentine** [druid-io/druid-operator#170]
Hi there, first of all, thanks for this awesome operator!

I'm just getting in touch because I'm attempting to deploy multiple Druid instances across multiple tenants. Our use case roughly is, I want to create users (who each have a namespace within k8s), a user-specific Druid instance. I was thinking to save duplicating some of the heavier components, running those in a dedicated namespace. For example, Zookeeper, Postgres, and I guess the overlords and the coordinators as a shared namespace. Then spinning up user-specific brokers, historicals and middlemanagers, and having those join the cluster. If that makes sense?

It seems theoretically possible to do this, and this operator seems to offer more granular control over the standard installation. So I guess my question is, does this operator support deploying across multiple namespaces? And if so, is there anything I should be aware of with this approach? 

Thanks in advance, any advice greatly appreciated 🙏🏻

**Comment by AdheipSingh** [comment]
@EwanValentine 

For you tenancy answer, the operator shall spin up all the druid nodeTypes ( coordinator, MM, brokers, router, historicals - hot/cold ) all in a single namespace. CRD is scoped to namespace. So a druid cluster per namespace is possible, however you can have multiple druid custom resources in a single namespace.

Operator shall watch events and reconcile the CR. Possibilities are 
- You can make an operator watch a single Namespace
- You can make an operator watch All namespace

The current druid operator does not support watching multiple namespaces. What the operator does provide you is a DENY_LIST, where you exclude the namespaces you dont want the operator to watch.

So what you can do is run the operator with ```WATCH_NAMESPACE=""``` ( watch all namespaces ) and add a ```DENY_LIST=default,kube-system```. 

I hope this answers you query. You can look at the docs here https://github.com/druid-io/druid-operator/blob/master/docs/getting_started.md#deny-list-in-operator

**Comment by AdheipSingh** [comment]
> That makes sense, about the operator being installed across all namespaces.

For a large environment it is too good to deploy a single operator which can watch all namespaces, at the same time filter out the namespaces which you don't want to reconcile using DENY_LIST.

> So are you saying it is possible to have, say the middlemanagers, brokers, and historicals etc, deployed separately into multiple namespaces? But joining the same Zookeeper instance, overlords and metadata database? Or would I have to roll out entirely separate clusters per tenant?

IMHO , it is possible to run a shared zookeeper and a metadata store. I am not sure about overlords. maybe @himanshug can help here. 

> I noticed the hot/cold concept mentioned in one of the examples, but I couldn't find a description of what this was in the docs.

Historical nodes can be configured to have tiers hot / cold. You can configure rules to load lets say 1 week data in hot and 3 month in cold tier. 

https://github.com/druid-io/druid-operator/issues/158#issuecomment-819224082

**Comment by EwanValentine** [comment]
Thanks for the info, really appreciate it!
