### ISSUE TITLE
Cluster Creation should be parallel, Rolling updates should be sequential 

### ISSUE THREAD

**Issue by AdheipSingh** [druid-io/druid-operator#177]
- When we have rolling deploy  set to true, upgrades are sequential. 
- When we have rolling deploy set to true, cluster creation is also sequential.
-------------------------------------------------------------------------------------------------------------------------------------------------------------
- A cluster can take upto 3-4 min of creation in a prod env. Which is slow, what we can do here is to make sure cluster creation is parallel regardless of rolling deploy set to true or false. 
-------------------------------------------------------------------------------------------------------------------------------------------------------------
- if ```sdkCreateOrUpdate()``` returns a ```CREATE``` string, we can ignore if ```ObjIsFullyDeployed()``` func,
- if ```sdkCreateOrUpdate()``` returns a ```UPDATE``` string, we can call if ```ObjIsFullyDeployed()``` func

@himanshug any thoughts on this ?

**Comment by himanshug** [comment]
it would be fine to start a brand new cluster in parallel. however, with proposed solution, one corner case is that if you update your druid spec by adding a/few new node spec, then sts/deployment for that would be a "CREATE" but cluster is actually being upgraded and not a new cluster so ` ObjIsFullyDeployed()` shouldn't be skipped.

so, maybe we should rely on some other signal to know whether it is the very first reconcile for a given spec. we can probably check for existence of "status" to know whether it is the first reconciliation or not.

**Comment by AdheipSingh** [comment]
makes sense, will give this a shot.

**Comment by AdheipSingh** [comment]
why not just use generation tag in the spec, if generation > 1 we call ```ObjIsFullyDeployed()```, on the first iteration ie cluster creation generation will be 1, on every change to cr generation will increase by +1. 

```
                                if m.Generation > 1 {
					// Check Deployment rolling update status, if in-progress then stop here
					done, err := isObjFullyDeployed(sdk, nodeSpecUniqueStr, m, func() object { return makeDeploymentEmptyObj() })
					if !done {
						return err
					}
				}
```

will send PR for this
