### ISSUE TITLE
Druid Node Status, Druid Cluster Status and Events 

### ISSUE THREAD

**Issue by AdheipSingh** [druid-io/druid-operator#190]
## ISSUE

- Currently the druid operator sends events on various state changes and actions it takes in order to meet the desired state of the CR. 
- The events emitted end up getting repeated and pollute the kubectl describe and get events cli calls.
- Ex: In case rolling update is ongoing, operator keeps on emitting events till the time rolling get deploy completes. This ends up with ROLLING_DEPLOY_WAIT event all over the describe of CR. This also pollutes kubectl get events :| 
- On further debug, as an operator i would like to get events only when a state change has occurred, if the previous state has not changed the operator should not send the event. This behaviour was seen in deployment controller of kubernetes where events are only emitted on state change.
- so the goal here is too make sure events are emitted only on state change, in case the previous state is same do not emit event. 

------------------------------------------------------------------------------------------------------------------------------------------------------------------------

## Approach

- After going through various approaches here's the approach i finalise, most of this is taken from the current controller implementations in upstream kubernetes.

- The first thing is here, we need to have an improved status of the Druid CR, which shall include 
1. DruidNodeTypeStatus - represents the state of each nodeType 
2. DruidClusterFinalStatus -  represents the cumulative state of all the nodeType

- Their is no way straight way to get druid final status, the operator runs a for loop reconciling each nodeType, at that particular moment we are aware of the current status of the particular nodeType.
- Ex: In case i trigger a rolling update which results in a cold nodeType crashing and other node types are still running, the DruidClusterFinalStatus should be NOT_READY at the same time DruidNodeTypeStatus should show the cold is NOT_READY. Event emitted should change from ROLLING_DEPLOYMENT_WAIT to COLD_NODE_CRASHING. Till the time the cold is not brought up the operator should not emit event.

- Events should check the state from status of the druid CR and get emitted, if prev state is still in-progress dont emit event.
- Druid Node Transition shall be displayed in the druid CR.
- On the basis of Druid Node Transitions we build the druid cluster final status.

**Comment by AdheipSingh** [comment]
will send a draft PR for this soon, for further discussions and design.

**Comment by himadrisingh** [comment]
what happens if druid operator gets restarted while updating and a tier has been crashing. Druid CR status should take care of it?

**Comment by AdheipSingh** [comment]
> what happens if druid operator gets restarted while updating and a tier has been crashing.

Druid Operator will re-run the reconcile loop and end up starting from where it left. If in any case the operator is down, the Druid CR Status remains constant to the last probe time changes, ie when was the last time status updated. Druid CR will need to be constantly patched by the operator on each reconcile on various state change.

Operator will try to maintain some state in the druid CR status to make event emitting decisions. As per my research i don't see this as anti-pattern in k8s controllers.

The only issue or pain is druid has 5/6 nodeTypes so might be tricky to see what func() fits in where.

Regardless, with this implemenation https://github.com/druid-io/druid-operator/issues/180 fix can also be introduced.

@himadrisingh

**Comment by AdheipSingh** [comment]
@himanshug let me know your thoughts on this, if any thing can be improved upon. :)

**Comment by AdheipSingh** [comment]
Another point id like to add in is, as of now when the druid-operator halts the rolling deploying when a cluster is upgrading and emits the event ```ROLLING_DEPLOYMENT_WAIT```.
What if at the point, the node is in an error state, the event emitted is still ```ROLLING_DEPLOYMENT_WAIT```, druid operator should be able to detect the underlying state of that pod, maybe get the ```podPhase``` of that pod and change event accordingly.
