### ISSUE TITLE
Operator Events not using client go record pkg ? 

### ISSUE THREAD

**Issue by AdheipSingh** [druid-io/druid-operator#195]
@himanshug i have few questions around the current implementations of the sendEvents()

- since i was spending some time in trying to fix the events polluting the describe of druid, i came across a standard implementations of events in k8s controllers.
1. DruidReconciler struct does not have any fields related to events records.
2. Any specific reason, you planned to keep events out of this struct. and not use pkg "k8s.io/client-go/tools/record" ? 
example:
```
// DruidReconciler reconciles a Druid object
type DruidReconciler struct {
	client.Client
	Log    logr.Logger
	Scheme *runtime.Scheme
	Record record.EventRecorder
	// reconcile time duration, defaults to 10s
	ReconcileWait time.Duration
}
```
- I see records pkg has a sink interface, where we can patch and update events rather than creating them each time. 
https://github.com/kubernetes/client-go/blob/master/tools/record/event.go#L47

- I also think since this Reconcile method implements the DruidReconciler, not sure how will deployDruid(), will use ```r.Record```, might need to create a custom interface as per druid operator use case. Just saying though :)

**Comment by AdheipSingh** [comment]
After trying different approaches with brodcaster, recorder ( client and controller runtime ), i conclude, events should be only  emitted in case of state change. State to be managed in CR status, Broadcaster and sink in client go are of little use, only helpful in case user want to listen to API events.
As far  operator is concerned it just want to emit events to the API so user can query through cli.
Current implementation of events function is using sdk.Create each time, the correct way is too add a recorder field in the DruidReconciler struct itself and use ```mgr.GetEventRecorderFor("")``` in the constructor for  DruidReconciler struct
Ill send a PR combined with state changes and events. Will be more clearer on the approach. 
Main goal is too reduce event pollution to make debugging easier. 
Open to suggestions :) 
cc @himanshug @nishantmonu51

**Comment by himanshug** [comment]
thanks for looking into it...

> Any specific reason, you planned to keep events out of this struct. and not use pkg "k8s.io/client-go/tools/record" ?
example:
I think record package did not exist at the time I wrote that code or I just missed it, but using that package makes sense.

Regarding reducing the number of events, I think we can add a config flag that sets the verbosity level of logs/events so that user can configure logs/events to be very quiet (only on error for example) or very chatty like it is today e.g. when trying to debug things.
