### ISSUE TITLE
Support topologySpreadConstraints

### ISSUE THREAD

**Issue by blatyo** [druid-io/druid-operator#208]
We would like to distribute our pods across multiple AZ's for availability. The only robust way to do that is by specifying [topologySpreadConstraints](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/). However, it appears the DruidSpec and DruidNodeSpec, don't accept the option or pass it along to the stateful set that's created behind the scenes.

**Comment by AdheipSingh** [comment]
sure operator can support this, would be nice to have.
