### ISSUE TITLE
Cannot batch ingest from HDFS

### ISSUE THREAD

**Issue by henriquekops** [druid-io/druid-operator#219]
Hi team,

I am facing connection problems when trying to ingest data from an external HDFS thorugh `index_parallel` task.

The HDFS service is available at port `8020`.

The `druid-hdfs-storage` extension is load correctly and the HDFS ingestion method is available at the console.

![image](https://user-images.githubusercontent.com/37592752/123324719-8655e780-d50d-11eb-989a-7e4e72061d2f.png)

It seems that any egress traffic from the pods deployed via the operator's `StatefulSet` cannot succeed. 

I've tried to telnet as follows, but it hangs:

```bash
$ kubectl exec -it druid-druid-cluster-routers-0 -n druid-cluster  -- sh
$ /opt/apache-druid-0.20.0# whoami
root
$ /opt/apache-druid-0.20.0# telnet 172.18.23.67 8020

```

I've tested the connection with other pods at the same namespace and the connection works fine.

```bash
$ kubectl exec -it zk-cluster-0 -n druid-cluster  -- bash
$ root@zk-cluster-0:/apache-zookeeper-3.6.3-bin# telnet 172.18.23.67 8020
Trying 172.18.23.67...
Connected to 172.18.23.67.
Escape character is '^]'.
^]
telnet> Connection closed.
```

By default on Kubernetes the ingress/egress rules should accept any source. Anyway, for tests purposes I've created the following `NetworkPolicy`, but the connection still not working:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress
  namespace: druid-cluster
spec:
  podSelector:
    matchLabels:
      app: druid
  policyTypes:
  - Egress
  - Ingress
  egress:
  - {}
  ingress:
  - {}
``` 

Any thouhts on that?

Regards.

**Comment by AdheipSingh** [comment]
> It seems that any egress traffic from the pods deployed via the operator's StatefulSet cannot succeed.

The operator roles is just to create a statefulset, it does not control any traffic or network policy associated with a ns or sts etc.
By default, egress/ingress are open to all traffic.

**Comment by nishantmonu51** [comment]
As @AdheipSingh mentioned the operator does not handle any network policies, 
Are you using istio or some other proxy for traffic handling? If yes, then you would need to separately configure it to allow traffic.

**Comment by henriquekops** [comment]
I couldn't figure it out, so switched to ingestion using S3 instead. Closing this for now.
