### ISSUE TITLE
[Question] Can this be used in production?

### ISSUE THREAD

**Issue by wemod123** [druid-io/druid-operator#220]
At title, this is just a question,

If this can be used in production, is there have a full process of document to say the steps to deploy a real scalable druid cluster on kubernetes

**Comment by AdheipSingh** [comment]
@wemod123 
yes this a production ready operator.
Kindly refer to the Docs to get started https://github.com/druid-io/druid-operator/tree/master/docs . 
The druid operator also has a helm chart to deploy druid operator. https://github.com/druid-io/druid-operator/tree/master/chart

Zookeeper and Metadata store is not provisioned or reconciled by the operator. That's a pre-requisite.

**Comment by wemod123** [comment]
@AdheipSingh 

Thank you for reply, what does that mean 

> Zookeeper and Metadata store is not provisioned or reconciled by the operator. That's a pre-requisite.

Sorry for this stupid question, where is the full documents to deploy a production druid with operator, if you assume you want to promote new users all around getting started experience?

**Comment by oliverdding** [comment]
@wemod123 Please refer to docs of druid. Druid need another three components to run, [deep storage](http://druid.apache.org/docs/latest/dependencies/deep-storage.html), [metadata storage](http://druid.apache.org/docs/latest/dependencies/metadata-storage.html) and [zookeeper](http://druid.apache.org/docs/latest/dependencies/zookeeper.html). You can find anything you want in that [website](http://druid.apache.org/docs/latest/design/index.html).
