### ISSUE TITLE
Restrict K8s role definitions to actually needed roles

### ISSUE THREAD

**Issue by DipeshCS** [druid-io/druid-operator#225]
We are planning to use Druid operator in Production at Zalando and we realized that [k8s role definition](https://github.com/druid-io/druid-operator/blob/master/deploy/role.yaml) is too generous giving access to lot more resources for operator than needed.  

Few examples would be:
- Usage of daemonsets is missing
- Usage of servicemonitors is missing
- Few resources use `*` but it is good practice to explicitly list them out
and many more.

It would be great if it can be fixed and made production-ready. 
Let me know if you need more information. 

Thanks

**Comment by AdheipSingh** [comment]
@DipeshCS 
agree with your observations and points listed out. Do you mind sending a patch and we can have it reviewed :)
Thanks
