### ISSUE TITLE
Deploy druid cluster across multiple namespace

### ISSUE THREAD

**Issue by cintoSunny** [druid-io/druid-operator#228]
Thanks for the awesome operator. I had a question, and wondering if you could help.

I want to deploy the Druid operator in one namespace (druid-dev) and the Druid cluster in another namespace(druid-stag). When I hardcode the target namespace name (druid-stag) in the operator yaml in the watch namespace section and create a role in the stag cluster, it works. 

But I need to add multiple namespaces to it. 

When I try to leave the watch namespace section empty (value: "") to support any namespace, it throws an error:
```E0713 20:08:43.335828       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1alpha1.Druid: druids.dataplatform.xxx.com is forbidden: User "system:serviceaccount:druid-dev:druid-operator" cannot list resource "druids" in API group "xxx" at the cluster scope
E0713 20:09:19.536133       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1alpha1.Druid: druids.dataplatform.xxx.com is forbidden: User "system:serviceaccount:druid-dev:druid-operator" cannot list resource "druids" in API group "dataplatform.xxx.com" at the cluster scope
```
Our company has a Kubernetes offering that does not allow the usage of clusterRoles. Any idea how we can do it with Roles and Role Binding. The suggestion is to use role and rolebinding in the target namespace, but I am not sure how to approach it.

Or can we pass multiple namespaces in the watch namespace section? If this works, then it would be fine too

**Comment by AdheipSingh** [comment]
Possibilities are

- You can make an operator watch a single Namespace
- You can make an operator watch All namespace
- The current druid operator does not support watching multiple namespaces. What the operator does provide you is a DENY_LIST, where you exclude the namespaces you dont want the operator to watch.

So what you can do is run the operator with WATCH_NAMESPACE="" ( watch all namespaces ) and add a DENY_LIST=default,kube-system.

Running the operator at cluster scope requires cluster roles and role binding. 

I hope this answers you query. You can look at the docs here https://github.com/druid-io/druid-operator/blob/master/docs/getting_started.md#deny-list-in-operator

We can add support for multiple namespaces if this something community needs cc @himanshug @nishantmonu51

**Comment by himanshug** [comment]
I think it would be fine to accept a list of namespaces to watch as well.

**Comment by cintoSunny** [comment]
Thanks guys. I actually made the change locally to watch a list of namespaces. And it is working fine. This is what I did:
I am checking if the namespace contains comma-separated values. If yes, then I am doing something like
```
options.NewCache = cache.MultiNamespacedCacheBuilder(strings.Split(namespaces, ","))
```
Along with some other minor code refactoring, this small change works just fine.

Now, we do not want to keep restarting the operator every time someone wants to add a new namespace. For that, I am working on fetching the values from a config map. I am working on that right now.

**Comment by AdheipSingh** [comment]
@cintoSunny great !! pls send a PR.

**Comment by himanshug** [comment]
> we are not too keen on restarting the operator every time we want to update the namespace list. We are not sure if that is a good practice. What do you think?

@cintoSunny I am not sure what is the concern if the operator is restarted. How often are you adding new namespaces in the list and did you really face problems because operator pod restarting whenever namespace list is updated [even when you used multiple replicas for operator pod]?

**Comment by AdheipSingh** [comment]
I have been updating deny lists, which also does cause restarts, but haven't faced any issues.

BTW, i gave this another thought https://github.com/druid-io/druid-operator/issues/228#issuecomment-907042019, the cache is initialised only at the start of main.go. Regardless of any approach to update the ns list cache will need to be re-synced and will need a restart. Since once the manager starts the controller, its the reconcile loop being executed.

**Comment by cintoSunny** [comment]
Thanks. Maybe it is a nice idea to try out this approach first. We will let you know if we see any issues.

**Comment by cintoSunny** [comment]
> @cintoSunny
> can't you put the values in configMap and get them as env variables in the pod using https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#define-container-environment-variables-using-configmap-data
> when you change the list of namespaces in configMap, your operator pod would be automatically restarted by k8s and if you need high availability then use multiple replicas for operator pod.

@himanshug: I do not think there is an automatic way for Kubernetes to restart the pod. The only feasible option I see is the run a rollout restart of the pod. 
```kubectl rollout restart deployment/busybox```
Correct me if I am missing anything.

**Comment by cintoSunny** [comment]
Looks like this is not merged yet.
