### ISSUE TITLE
Operator is logging RPC errors

### ISSUE THREAD

**Issue by henriquekops** [druid-io/druid-operator#235]
Hi team!

One of my coordinators (1/2) was not responding to liveness probes at `/status/health`, so after some time I tried to restart it, but it was not enough.

When I scaled it down, I've noticed that the statefulset was not aware of the terminating pod:

```
$ kubectl get sts -n druid-cluster

NAME                                                  READY   AGE
...
druid-druid-cluster-coordinators          0/0       13d
...
```

Looking through the operator's log I found this error:

```
2021-08-12T12:56:37.562Z	ERROR	druid_operator_handler	failed to patch status object for [Druid:druid-cluster] due to [rpc error: code = Unavailable desc = transport is closing]	{"name": "druid-cluster", "namespace": "druid-cluster", "error": "failed to patch status object for [Druid:druid-cluster] due to [rpc error: code = Unavailable desc = transport is closing]"}
```

As a quick fix I restarted the operator's pod, but then the problematic coordinator's pod became a "zombie" process in Kubernetes, it doesn't terminate in any manner:

```
...
druid-druid-cluster-coordinators-0                          0/1     Terminating   0          2d21h
...
```

Any advices on how to solve this problem?

**Comment by AdheipSingh** [comment]
i personally haven't faced this error, this seems like an error returned from the ```etcd```
As per flow, in order to scale down any druid node the correct way is too edit the druid CR replica count for that node. and operator shall send the request to sts controller/object which shall process the final scale down.

Did you edit the sts directly ? and not the CR while scale down, assuming that might have caused confusion.

Regardless this definitely an error response from the API > etcd. In case the pod is hard stuck, try deleting the statefulset, the operator should re-create it on the next reconcile loop.

**Comment by AdheipSingh** [comment]
> I have scaled the statefulset directly through kuebctl.

I just not to scale the sts directly when using operator. Always edit the druid CR replica count field in the nodeSpec of each druid node.

This seems like K8s internal issue, not sure if this is an operator issue, as you can see the statefulset-controller response can't POST to the API.
Operator relies on statefulset/deployment controllers to scale up replica counts.

Do you see this issue with some dummy sts  too ? ( i mean  try creating some dummy nginx sts, and see it you have the same issue ).

**Comment by henriquekops** [comment]
> Do you see this issue with some dummy sts too?

Yeah, turns out that the problem was about my insfrastructure, running k8s in bare metal is a hard task...

This error seems to be a problem at the communication between the controller and worker nodes.

My problem was at VM level, nothing to do with the operator itself. When updating the virtualization service some VMs got down w/ no 'drain', so hypervisor got lost and everything went buggy. Was necessary to reboot to get everything working properly again.

Closing this issue for now.
