### ISSUE TITLE
Deploy druid cluster in Service Account and support ImagePullSecrets

### ISSUE THREAD

**Issue by AdheipSingh** [druid-io/druid-operator#24]
I propose to deploy the druid cluster in a service account so that adequate RBAC's can be applied in a prod environment. 
Currently operator cannot pull custom built images private registeries which require authentication, add support for ImagePullSecrets option in sts.
Currently only the operator runs in a SA. Not sure  adding SA in druid cluster spec should it be a Required or Optional Parameter ? 
@himanshug could you suggest on service account

**Comment by himanshug** [comment]
service account should be optional as it can always work with default service  account configured, as it  does today.

aside from that all sgtm.
