### ISSUE TITLE
Update operator version at operator hub

### ISSUE THREAD

**Issue by henriquekops** [druid-io/druid-operator#269]
I see at the [operator hub](https://operatorhub.io/operator/druid-operator) that it is pointing to version 0.0.6. Can it be updated to the latest tag?

**Comment by AdheipSingh** [comment]
@henriquekops will do this week for sure.

**Comment by AdheipSingh** [comment]
https://github.com/k8s-operatorhub/community-operators/pull/711

**Comment by henriquekops** [comment]
Thanks @AdheipSingh  !
