### ISSUE TITLE
Deploying on minikube

### ISSUE THREAD

**Issue by ayush9398** [druid-io/druid-operator#27]
Hello,

I am trying to setup druid locally on minikube, anyone help please. Right now, when I try to do it, the cluster pods do't run due to the resource limits set.

Thanks!

**Comment by AdheipSingh** [comment]
Hi,
Try to run your minikube by giving it some extra resources ```minikube start --memory=16384 --cpus=6 ``` , depending upon your systems. Try reducing the resources to 1 each CPU and memory in the yaml, it should run easily.

**Comment by ayush9398** [comment]
I got 8gb ram and i5 8th gen cpu. I think cpus would be fine but I am low on memory side.

**Comment by ayush9398** [comment]
I have 8gb ram and i5 8th gen. Cpus should be fine but I am low on memory side I think.

**Comment by ayush9398** [comment]
Thanks @AdheipSingh , got it working in minikube.

I am facing another issue now, I was using `kubectl proxy` now, and trying to access the coordinator  and navigating to `http://localhost:8001/api/v1/namespaces/default/pods/druid-tiny-cluster-coordinators-0/proxy/index.html#/`
in browser, but all i can see is:

![Screenshot from 2020-03-23 11-25-18](https://user-images.githubusercontent.com/21312552/77286385-1bf63c00-6cf9-11ea-8752-847c87ea1217.png)

Error in browser console: 

![Screenshot from 2020-03-23 11-28-22](https://user-images.githubusercontent.com/21312552/77286537-7394a780-6cf9-11ea-9404-5c12c29507e4.png)

Please help.

**Comment by AdheipSingh** [comment]
i haven't used kube-proxy, i prefer to use ```kubectl port-forward``` command. try to port-forward the coordinator pod and check for coordinator logs for errors.

**Comment by ayush9398** [comment]
Ohk Thanks!

**Comment by himanshug** [comment]
@ayush9398 it will be useful if you could document here steps for setting up deploying druid cluster on using this operator and your spec to get things working. thanks.
that might help potential users trying to do same.

**Comment by ayush9398** [comment]
@himanshug Actually, I am still working on it. I came across druid helm chart and for now my problem is solved through it. If I am able to solve this, I will document it surely!
