### ISSUE TITLE
Bump up chart version to 0.1.2

### ISSUE THREAD

**Issue by youngwookim** [druid-io/druid-operator#271]
Operator version was bumped up to 0.0.8, https://github.com/druid-io/druid-operator/commit/017d40e3119c35ba1fae3143f2c9e2f1aab184b9

Should be updated the chart's version to 0.1.2 as well.

**Comment by AdheipSingh** [comment]
@youngwookim 
each time operator is version is released, the appVersion is updated in helm.
In case any changes went in the helm chart, in that case we update the chartVersion. 

In release 0.0.8 no changes were made to helm chart, so the version remains the same.

**Comment by youngwookim** [comment]
@AdheipSingh Thanks for your clarification on versioning chart.
Actually, chart version is not independent from appVersion of druid operator. At [1], the tag name is the appVersion by default. In this case, users will have unexpected results from same chart version. For instance, if I have two cluster with the same version(0.1.1) of druid-operator, I would expect that same operator working on each cluster but, the output of templating of chart will keep changing by the appVersion.

I know that there are workarounds for that cases but, if output of chart with same version is changing, it would be good to update chart version to avoid confusing and also it'll make easier to upgrade chart to newer version.

1. https://github.com/druid-io/druid-operator/blob/master/chart/templates/deployment.yaml#L33
