### ISSUE TITLE
Roll Out Release

### ISSUE THREAD

**Issue by AdheipSingh** [druid-io/druid-operator#29]
HI, can we roll out a release mentioning the features added.

**Comment by himanshug** [comment]
sure, will do that after https://github.com/druid-io/druid-operator/pull/28  is done.

**Comment by AdheipSingh** [comment]
@himanshug thank you :)

**Comment by himanshug** [comment]
0.0.2 image is available  now https://hub.docker.com/r/druidio/druid-operator/tags
