### ISSUE TITLE
Coordinators Scenarios  

### ISSUE THREAD

**Issue by AdheipSingh** [druid-io/druid-operator#30]
Here are some of my coordinators issues/doubts while running druid on k8s

1. Coordinator follow leader election, meaning at a single time only one coordinator is active. So in case of HPA, if coordinator scales to lets say 2 pods, the request to coordinators is not still being load balanced as only one of them is a leader. The idea of HPA is to scale so that multiple pods can handle a request with the service load balancing it. 

2. For  HA architecture keeping in mind quorum, fault tolerance etc always have at least 3 coordinators ? Is it recommended ?

3. I want to expose the coordinator service to the end users so that can POST their ingestion specs to the coordinator. If i use ingress to expose it, i need the ingress to  point it to the coordinator service. Now how does the k8s service know which coordinator is active between the 3 coordinators, i know druid has zookeeper for service discovery but that's for druid's internal service discovery, an HTTP request routing through an ingress and k8s service doesn't know which coordinator to hit to ( basically that's k8 service ). 

I may be not conceptually aware about druid coordinator mechanisms, i am thinking about these more from a k8s perspective. 

Thank you

**Comment by himanshug** [comment]
only one leader coordinator  node is active  at any time, so  hpa  is not much help.  you only  need two replicas, "quorum" is needed by zookeeper nodes  (3 or 5 or whatever) not coordinator nodes

request to non-leader nodes are always redirected to leader node , so  you wouldn't want to expose coordinator to end user or else they will need the capability to reach coordinator leader pod directly.

"router"  is the right  thing  to  expose which knows how to proxy requests to leader coordinator node. that said, if "end user" is people inside your company then it is fine , if not, then it is probably not great to expose any of druid nodes to the "end user".

**Comment by AdheipSingh** [comment]
So it get it best is not to use  HPA for coordinators. Make sense to use only routers to expose the any of druid ep. I guess ill need to add an ingress spec support in the nodeSpec of the CR.

Thank You @himanshug
