### ISSUE TITLE
Helm chart templates for roles and service accounts are not correct

### ISSUE THREAD

**Issue by zhangluva** [druid-io/druid-operator#308]
There are a few problems there in the templates.
1) Doc says the operator can watch multiple namespaces, by setting `env. WATCH_NAMESPACE=NS1,NS2`. But the [templates](https://github.com/druid-io/druid-operator/blob/5abef01594ff953ba8a092aa7d392c06d682b167/chart/templates/role.yaml#L3-L9) do not handle multiple namespaces.
2) Permissions on `storage.k8s.io` is needed, otherwise `scalePvcSts` won't work

**Comment by AdheipSingh** [comment]
@zhangluva feel free to submit a patch. 
Thanks for pointing this out
