### ISSUE TITLE
Fix ci 

### ISSUE THREAD

**Issue by vDMG** [druid-io/druid-operator#32]
I think there is a strange behaviour with the `Makefile` on this part
```
fmt:
	test -z $$(gofmt -l -s pkg/apis/druid/v1alpha1/druid_types.go)
	test -z $$(gofmt -l -s pkg/controller/druid)
```

I'm not sure about the best way to fix it

**Comment by gl** [comment]
Just a formatting issue in handler.go
a run of "gofmt -w pkg/controller/druid/handler.go" fixes it

**Comment by vDMG** [comment]
Indeed, thank you @gl !
