### ISSUE TITLE
Support for EKS is the 1.24 supported

### ISSUE THREAD

**Issue by maheshevizio** [druid-io/druid-operator#322]
Could you please confirm if I can use eks 1.24,23 or 22 ?
Or the latest version that is supported for this druid-operator

Thanks

**Comment by AdheipSingh** [comment]
yes operator should support. I haven't tested it on eks personally.

**Comment by maheshevizio** [comment]
Thank you! I have installed and it works fine on 1.20 EKS. Wanted to setup a new cluster for another environment with 1.24 EKS, hence the above question
