### ISSUE TITLE
Requesting Druid PMC for write permission on repo 

### ISSUE THREAD

**Issue by AdheipSingh** [druid-io/druid-operator#329]
- its getting hard to maintain the repo without any access to merge PR's, cut releases and contribute to the repo.
- i have been individually reaching out to druid PMC having write access to the repo, to merge PR's and cut releases.
- currently, to merge a PR and cut releases it takes months.
- the repo has immense potential and needs massive improvements and enhancements. 

A humble request to druid PMC to help in maintaining the repo by at least granting write access to merge PR's and cut releases.

@himanshug @fjy @gianm @nishantmonu51 @xvrl

**Comment by jwitko** [comment]
@himanshug @fjy @gianm @nishantmonu51 @xvrl
Any chance for some action on this?  @AdheipSingh has been doing great work

**Comment by gianm** [comment]
Unfortunately, this is a legacy repository that the Apache Druid PMC doesn't control. Some PMC members have access as individuals, but the PMC as a whole does not. IMO, it's best to move away from this repository in one of two ways:

1) Someone that wants to maintain it does the legwork to get it donated to ASF, so it can become an official part of Apache Druid. Most of the legwork here is IP Clearance: https://incubator.apache.org/ip-clearance/

2) Someone that wants to maintain it forks it, and we update the readme on this repo to point to the new fork.

**Comment by AdheipSingh** [comment]
> Someone that wants to maintain it forks it, and we update the readme on this repo to point to the new fork.

This would be the most feasible approach for long term. I will maintain the fork, also calling in for collaborators , this project has great potential for becoming a control plane for running apache druid. 

cc @cintoSunny @harinirajendran @himanshug

**Comment by nitisht** [comment]
> I will maintain the fork, also calling in for collaborators 

This is great news, @AdheipSingh. Excited for the future of Druid Operator

**Comment by cintoSunny** [comment]
This is really great news. We have been thinking of similar options since the druid operator is integral and there hasn't been much movement recently.

**Comment by harinirajendran** [comment]
Thanks, @AdheipSingh !! So, going forward, should we fork off from your fork then? Can you provide us with the details once the new fork is set up?

**Comment by AdheipSingh** [comment]
By end of this week. Yes feel free to fork. It would be great to add in collaborators from your teams.

**Comment by AdheipSingh** [comment]
I have moved the repo to https://github.com/cloudnativelyhq/druid-operator 

- since its inception druid-io/druid-operator has a lot of stale issues, i will migrate all the issues relevant. 
- the docker images release are pushed to druid-io docker repo. The previous tagged releases will have the same docker image as it is. Moving forward will move on the release and docker images.

**Comment by gianm** [comment]
Thanks @AdheipSingh! Merged your PR #336 as well.
