### ISSUE TITLE
Operator should delete PVC once CR is deleted

### ISSUE THREAD

**Issue by AdheipSingh** [druid-io/druid-operator#43]
- Currently the operator does not remove PVC's after the CR has been removed.

### Proposal
- In the types.go have a volumeReclaimPolicy if set to delete, the operator should clear up the pvc associated with that CR.
- Ideal way is to have a finalizer which shall run up clean up task to remove pvc. 
-------------------------------------------------------------------------------------------------------------------------------
- Additionally the operator should also support cleaning of pvc's which are not mounted or referenced by the CR pods. Statefulset do not delete the pvc associated by the pod. so incase of scale up/down pvc's keep on hanging up. This can also be added optionally.

@himanshug

**Comment by himanshug** [comment]
I thought this would get complex and really should be delegated to statefulSett. I have been kind of hoping that https://github.com/kubernetes/kubernetes/issues/55045 discussion will resolve someday opening a clear path  for this.

**Comment by AdheipSingh** [comment]
I don't think its too complex, finalizer's can run pre-delete hooks and clear the pvc's. The whole concept of the operator is too make as minimal manual efforts to run applications. After removing CR, need to delete atleast 6 pvc'. Can't really comment on when these issue will be resolved from k8s, i see issue opened 2 years back :) .
If you have any other simpler way do tell. But ideally finalizer is the way to go.

**Comment by himanshug** [comment]
By  finalizer, do  you mean using a preStop script as in https://github.com/druid-io/druid-operator/pull/42 ?
that would always delete the PVC when pod is stopped which happens very often in k8s env, no ?
