### ISSUE TITLE
Ability to define cold and hot historical in Node Spec

### ISSUE THREAD

**Issue by AdheipSingh** [druid-io/druid-operator#44]
###### ISSUE
- Historicals can be associated with a tier cold, hot or default . As a user i should be able to specify whether my historical is cold or hot.
- NodeType key only accepts "historical" https://github.com/druid-io/druid-operator/blob/0d843a4cd3b4aebfa13c2144ebdab2998f6de9e2/pkg/controller/druid/handler.go#L960 
- Plus the pod names are based on this key. 
https://github.com/druid-io/druid-operator/blob/0d843a4cd3b4aebfa13c2144ebdab2998f6de9e2/pkg/controller/druid/handler.go#L418
------------------------------------------------------------------------------------------------------------------------------------
- To have this possible we can add a ```Name string `json:"name"` ``` in types.go and the use it as unique identifier for different nodes. This gives more flexibility. Can define what ever combination  my node is. 
```
func makeNodeSpecificUniqueString(m *v1alpha1.Druid,n *v1alpah1.DruidNodeSpec) string {
	return fmt.Sprintf("druid-%s-%s", m.Name, n.Name)
}
```
Looking for any other approach with minimal changes to existing code base
@himanshug

**Comment by himanshug** [comment]
this should already be possible by defining two nodespecs for historicals with different key for  the nodespec.. e.g.

```
...
...
    hot-tier-historicals:
      nodeType: "historical"
      druid.port: 8088
      nodeConfigMountPath: "/opt/druid/conf/druid/cluster/data/historical"
      replicas: 1
      runtime.properties: |
        druid.tier=hot
        druid.service=druid/historical
        druid.server.http.numThreads=5
        druid.processing.buffer.sizeBytes=1
        druid.processing.numMergeBuffers=1
        druid.processing.numThreads=1
...
...
    cold-tier-historicals:
      nodeType: "historical"
      druid.port: 8088
      nodeConfigMountPath: "/opt/druid/conf/druid/cluster/data/historical"
      replicas: 1
      runtime.properties: |
        druid.tier=cold
        druid.service=druid/historical
        druid.server.http.numThreads=5
        druid.processing.buffer.sizeBytes=1
        druid.processing.numMergeBuffers=1
        druid.processing.numThreads=1
...
...
```

**Comment by AdheipSingh** [comment]
ok thank i'll take a look. Might have missed on this.
