### ISSUE TITLE
nodeSelector missing in DruidNodeSpec

### ISSUE THREAD

**Issue by gl** [druid-io/druid-operator#55]
It's not possible to use nodeSelector inside a DruidNodeSpec as it's defined only at global level. Trivial workaround is to use affinity, but it's inconsistent.

**Comment by AdheipSingh** [comment]
@gl yeah its global currently. BTW curious to know what is in-consistent with affinities.:)

**Comment by himanshug** [comment]
Affinity is more general and I think NodeSelector should never be really used now. @gl , @AdheipSingh is there any use case for using NodeSelector ?

**Comment by AdheipSingh** [comment]
I dont think their is any generalised usecase since it all depends on the user, how he assigns different pods to nodes. Good scheduling practices can definitely help to scale druid pods. At the same time no harm in adding scope in nodes too. :) 
Though the better approach is to use nodeAffinity.

**Comment by gl** [comment]
I was unclear, I meant that it is inconsistent to not have affinity and nodeselector usable at the same places in the config. Affinity is working fine :)

**Comment by AdheipSingh** [comment]
yes make sense :) @gl
