### ISSUE TITLE
example add router

### ISSUE THREAD

**Issue by jinleileiking** [druid-io/druid-operator#56]
router is needed!

**Comment by AdheipSingh** [comment]
@jinleileiking 
https://gist.github.com/AdheipSingh/cee71aecc1a0cd0f6ccf4cbcb324fc4d#file-gistfile1-txt-L720
You can add this way. Hope it helps :)

**Comment by beni20** [comment]
yep router/console might be nice to have:)
https://github.com/druid-io/druid-operator/pull/67
