### ISSUE TITLE
Release 0.03

### ISSUE THREAD

**Issue by AdheipSingh** [druid-io/druid-operator#66]
@himanshug 
Please cut out a release. Here's a change log to refer too
### Change Log
-  go modules updated to kubernetes 1.16.2
-  Support for Deployments
-  Ingress, containerSecurityContext. LifeCycle and ReadOnly for ConfigMaps added

**Comment by himanshug** [comment]
a release is cut and new docker image is available in dockerhub as well.

@AdheipSingh thanks for your contributions.
