### ISSUE TITLE
docker hub latest tag

### ISSUE THREAD

**Issue by beni20** [druid-io/druid-operator#68]
any reason to not tag docker images with latest tag? Generally ppl are interested in latest version and lazy to check what versions we have there;)

> Error response from daemon: manifest for druidio/druid-operator:latest not found: manifest unknown: manifest unknown

**Comment by AdheipSingh** [comment]
@beni20 latest tag end up breaking changes, i prefer tag to know which version is compatible. Even apache/druid does not have any latest tag.

**Comment by beni20** [comment]
@AdheipSingh thx i will close this issue.
btw i still believe its slightly confusing to not have latest tag eg go to https://hub.docker.com/r/druidio/druid-operator
there is command to invoke docker which simply doesnt work as I believe Docker guys assume latest tag is good practice to have 
docker pull druidio/druid-operator

**Comment by AdheipSingh** [comment]
@beni20 sure @himanshug  can take a look at it. 
I am fine with both :)

**Comment by himanshug** [comment]
`latest` tag is available now.

I wouldn't get in the debate about goods/bads/misunderstandings of `latest` tag , there is enough said on the internet already :)
