### ISSUE TITLE
SubPath in ConfigMaps

### ISSUE THREAD

**Issue by AdheipSingh** [druid-io/druid-operator#78]
@himanshug 

While using a custom entry point for druid, which substitutes some env values during initialisation of pods, i saw the config maps getting mounted were nt able to get copied to the right directory as in the entry point script. something equivalent too [https://github.com/apache/druid/blob/master/distribution/docker/druid.sh#L49](https://github.com/apache/druid/blob/master/distribution/docker/druid.sh#L49) 

i ended up adding subPaths to the configmaps, which basically solved that problem. 
We should have in general too avoid confusion.

```
volumeMount := []v1.VolumeMount{
		{
			MountPath: m.Spec.CommonConfigMountPath + "/common.runtime.properties",
			Name:      "common-config-volume",
			ReadOnly:  true,
			SubPath:   "common.runtime.properties",
		},
		{
			MountPath: m.Spec.CommonConfigMountPath + "/log4j2.xml",
			Name:      "common-config-volume",
			ReadOnly:  true,
			SubPath:   "log4j2.xml",
		},
		{
			MountPath: nodeSpec.NodeConfigMountPath + "/jvm.config",
			Name:      "nodetype-config-volume",
			ReadOnly:  true,
			SubPath:   "jvm.config",
		},
		{
			MountPath: nodeSpec.NodeConfigMountPath + "/runtime.properties",
			Name:      "nodetype-config-volume",
			ReadOnly:  true,
			SubPath:   "runtime.properties",
		},
```

**Comment by himanshug** [comment]
you mean replace https://github.com/druid-io/druid-operator/blob/master/pkg/controller/druid/handler.go#L636 with the code snippet in your description ?

sorry, I couldn't understand the problem really.

**Comment by AdheipSingh** [comment]
sorry i explain bad.

My thought is we should have subPaths as shown in the code snippet, subPaths in general is a good practice since we are dealing with multiple configmaps + when user uses custom entry point they might run into the issue which i ran into, so it would be good if we include subPaths in handler.go ( i was able to solve my issue using subPaths ) :)

Hope that makes sense :)

**Comment by himanshug** [comment]
I still did not understand the problem.

That said, listing down all those files explicitly in code means we know of all the possible files... however by just letting k8s create all files from list in configMap allows user to have any files in common config e.g. some users create additional files like the "mapping file" optionally used by statsd emitter.

**Comment by AdheipSingh** [comment]
oh sorry for my explanations having messing too much with druid lately :laughing: 

Simple question, should we use subPaths as describe in the snippet or not ? 
If not why ? 



> That said, listing down all those files explicitly in code means we know of all the possible files... however by just letting k8s create all files from list in configMap allows user to have any files in common config e.g. some users create additional files like the "mapping file" optionally used by statsd emitter.

The operator does not support creating any additional conifgmaps right ? like apart from log,jvm, common and runtime

**Comment by himanshug** [comment]
> The operator does not support creating any additional conifgmaps right ? like apart from log,jvm, common and runtime

operator actually doesn't control it currently, it just creates a file for each entry in common configMap. operator would already be creating all those files, I am not sure what is accomplished by listing them explicitly.
I guess I am probably not able to figure out the problem you faced when they are not listed explicitly in the code :(  . Is there a way I can reproduce the problem you faced?

**Comment by AdheipSingh** [comment]
i wish i could help you to re-create the problem but the script and image are custom and does a bunch of things on entry point...
Ill close this issue, i dont think anyone will face with the oss version of druid,unless someone fiddles around the entrypoint and mount points for configuratons.
