### ISSUE TITLE
AutoScaling Using HPA 

### ISSUE THREAD

**Issue by AdheipSingh** [druid-io/druid-operator#8]
I plan to add HPA autoscaling support in the types definition, for all the nodes ie historical, middle managers and brokers. Currently need to manually add after the operator deploys the druid cluster. Here a prototype which can be included in the nodeSpec, can keep this feature optional.
```
type AutoScaleSpec struct {
	Autoscale *bool `json:"autoscale,omitempty"`
	Replicas *int32 `json:"replicas,omitempty"`
	MinReplicas *int32 `json:"minReplicas,omitempty"`
	MaxReplicas *int32 `json:"maxReplicas,omitempty"`

```

**Comment by akashdw** [comment]
👍 , could you add it in the cluster and node spec bot?

**Comment by AdheipSingh** [comment]
Sure I'll be adding a seperate struct for autoscale, and call in the cluster and nodespec and keep it as pointers so thats its optional...... I guess HPA should be optional, or default ? what do you think @akashdw
```
type AutoScaleSpec struct {
	Autoscale *bool `json:"autoscale,omitempty"`
	Replicas *int32 `json:"replicas,omitempty"`
	MinReplicas *int32 `json:"minReplicas,omitempty"`
	MaxReplicas *int32 `json:"maxReplicas,omitempty"`
```
```
type ClusterSpec struct {
        Scale *AutoscaleSpec `json:"scale"`
}
```

```
type NodeSpec struct {
        Scale *AutoscaleSpec `json:"scale"`
}
```

**Comment by AdheipSingh** [comment]
created PR for it, https://github.com/druid-io/druid-operator/pull/11
