### ISSUE TITLE
ClusterIP service type change does not take effect without manual intervention

### ISSUE THREAD

**Issue by talonx** [druid-io/druid-operator#83]
- Don't set "clusterIP: None" under the services spec for middle managers (this leads to a broken cluster, since it's needs to be headless, but this is a real example) while creating a cluster
- Cluster is up, with the service type set to ClusterIP and a virtual IP assigned.
- Add "clusterIP: None" and kubectl apply with `rollingDeploy: true`

Expected : the service type should change to headless. But it does not until I manually delete the service and the operator reconciles it to the correct state.

The operator logs show that it sees both "Prev Object" and "Updated Object" with the IP addr assigned.

**Comment by AdheipSingh** [comment]
hmm i got your point, can you share your config, will be faster to debug issue.

BTW why does have a clusterIP lead to a broken state ? just curious to know :)

**Comment by AdheipSingh** [comment]
operator is fine, k8s does not allow ClusterIP to be change to None, as this field is immutable. 
Ideally the operator is doing the right thing to make sure they are always ==

You can try out by using simple svc manifest, you ll get the same behaviour.

**Comment by talonx** [comment]
> operator is fine, k8s does not allow ClusterIP to be change to None, as this field is immutable.

Ah, thanks for clarifying this.

> BTW why does having a clusterIP lead to a broken state ? just curious to know :)

Unless it's a headless ClusterIP, DNS resolution fails for coordinator pods attempting to talk peon processes inside the middle manager pod using the latter's FQDN, which would look something like

`http://druid-staging-middlemanagers-0.druid-staging-middlemanagers.default.svc.cluster.local:8102`
