### ISSUE TITLE
Ability to watch a subset of namespaces

### ISSUE THREAD

**Issue by AdheipSingh** [druid-io/druid-operator#88]
# ISSUE
- Currently operator supports 
1. Watch all namespaces
2. Watch specific namespace

I want the operator to watch all namespace **BUT** 
- There are Few namespaces are critical from security perspective, i dont want the operator too watch
- Testing is not possible if you are running operator cluster scope and if you want to test a feature you need to scale down the operator and run locally or else get confused which operator is re-reconciling your CR
- As a user i should be  able to define which namespace the operator can watch OR a list of namespaces the operator can neglect 
- Excluding Namespaces can be bit of more work, since we might need to use **Predicates** for event filtering to exclude events to be processed from the given namespace. 

## IMPLEMENTATION 

- Use this package in main.go and provide a slice of string string as namesapce https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/cache#MultiNamespacedCacheBuilder
- main.go can be changed to use this package
- What this should like 
```
ENV: WATCH_NAMESPACE 
"" - watch  all namespace
string - watch particular namespace
[]string - watch namespaces which i want
```

**Comment by himanshug** [comment]
so it is like a `allowList` and/or `denyList` of namespaces feature ... sounds good to me.

**Comment by AdheipSingh** [comment]
yes exactly, ```allowList``` is pretty straightforward with CacheBuilder, in order to ```denyList``` we need to use predicates, to ignore events from that namespace. Though this can be also done in the reconcile request which includes Namespace but predicates will be one step up further for filtering events

**Comment by AdheipSingh** [comment]
So i tested predicates to create a denyList, here i think what we can do :

All these go as values for ```WATCH_NAMESPACE``` in operator deployment yaml
1. Watch single Namespace ...... ```string```
2. Watch All Namespace ............ ``` " " ```
3. Watch Subset Namespace ...... ```[]string``` ### Here use multiNamespace package

Pass Args/Flags for denyList which shall go into predicates to filter event as 
```
 command:
          - druid-operator
          - --denyList=["namespace", "deny"] ### Here use predicates
```

Here's what a simple func looks like
```
func ignoreNamespacesPredicate() predicate.Predicate {
	return predicate.Funcs{
		CreateFunc: func(e event.CreateEvent) bool {
			log.Info("druid-operator will not reconcile to the namespace [%s]", e.Meta.GetNamespace)
			if e.Meta.GetNamespace() == "gcs-test" {
				return false
			}
			return true
		},
		UpdateFunc: func(e event.UpdateEvent) bool {
			log.Info("druid-operator will not reconcile to the namespace [%s]", e.MetaNew.GetNamespace)
			if e.MetaNew.GetNamespace() == "gcs-test" {
				return false
			}
			return true
		},
	}
}
```
we can then hook this into the controller watcher 

```
err = c.Watch(&source.Kind{Type: &druidv1alpha1.Druid{}}, &handler.EnqueueRequestForObject{}, ignoreNamespacesPredicate())
	if err != nil {
		return err
	}
```

@himanshug  let me know if you would like some permutations and combinations to be changed here, ill draft a working PR soon. 

cc @nishantmonu51
