### ISSUE TITLE
druid.sdkCreateOrUpdateAsNeeded to first get and then create the resource

### ISSUE THREAD

**Issue by akashdw** [druid-io/druid-operator#9]
The current implementation of this method first tries to create the resource and then checks for `metav1.StatusReasonAlreadyExists` error. I have come across some custom admission webhook that might not return the `metav1.StatusReasonAlreadyExists` error to indicate already existing resources.
This proposal is to change the sdkCreateOrUpdateAsNeeded method(also rename the method to `sdkCheckAndCreate`) to first get the resource and create only if the resource doesn't exist.
I tested out the above changes in our prod environment and will create a pr for these changes.

**Comment by AdheipSingh** [comment]
Could you highlight what the nature of the webhook, i plan to run some validating webhooks, just want to make sure it does'nt impact.

Since you are running it on prod, do you mind adding some docs. It would help for sure :)

**Comment by akashdw** [comment]
@AdheipSingh For our case, it was a custom admission webhook for PDB, and that webhook was restricting the duplicate PDB and failure did not have `metav1.StatusReasonAlreadyExists`. 
The idea here is not to completely rely on `metav1.StatusReasonAlreadyExists` and make the operator more resilient towards these kinds of failures.

Could you describe a little bit more about what you need in the doc?

**Comment by AdheipSingh** [comment]
@akashdw understood. For the doc, we could add a folders docs with examples of running configurations for prod, any specific tuning parameters would helpful.
