### ISSUE TITLE
operator should allow scale replicas to zero

### ISSUE THREAD

**Issue by AdheipSingh** [druid-io/druid-operator#99]
- validation , has replicas < 1, which leads not to scale to zero.
- incase ingestion/querying not happening MM/brokers or even hot/cold can be scaled to zero.
- i guess we can remove replicas from validation ?

**Comment by himanshug** [comment]
can't see any problem with that as long as StatefulSet/Deployment don't complain if replica = 0 .

**Comment by AdheipSingh** [comment]
nopes, nothing should complain
